site_name: Pocket Doc

# site_url: http://pocketdoc.org/home
theme:
  name: material

  font:
    code: Roboto Mono

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference

markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 2
      # separator: "_"
